In [ ]:
# 刘佳昌
# 5班
# 2016011565

In [1]:
import tensorflow as tf

D:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
#创建张量
a = tf.range(10*28*28*3)
new_a = tf.reshape(a,[10,28,28,3])

In [5]:
#利用索引取出第二张图片 索引为1
with tf.Session() as sess:
    res_1 = sess.run(new_a[1])
    print(res_1)

[[[2352 2353 2354]
  [2355 2356 2357]
  [2358 2359 2360]
  ...
  [2427 2428 2429]
  [2430 2431 2432]
  [2433 2434 2435]]

 [[2436 2437 2438]
  [2439 2440 2441]
  [2442 2443 2444]
  ...
  [2511 2512 2513]
  [2514 2515 2516]
  [2517 2518 2519]]

 [[2520 2521 2522]
  [2523 2524 2525]
  [2526 2527 2528]
  ...
  [2595 2596 2597]
  [2598 2599 2600]
  [2601 2602 2603]]

 ...

 [[4452 4453 4454]
  [4455 4456 4457]
  [4458 4459 4460]
  ...
  [4527 4528 4529]
  [4530 4531 4532]
  [4533 4534 4535]]

 [[4536 4537 4538]
  [4539 4540 4541]
  [4542 4543 4544]
  ...
  [4611 4612 4613]
  [4614 4615 4616]
  [4617 4618 4619]]

 [[4620 4621 4622]
  [4623 4624 4625]
  [4626 4627 4628]
  ...
  [4695 4696 4697]
  [4698 4699 4700]
  [4701 4702 4703]]]


In [7]:
#利用切片取出第二张图片
b = tf.slice(new_a,[1,0,0,0],[1,28,28,3])
with tf.Session() as sess:
    res_2 = sess.run(b)
    print(res_2)

[[[[2352 2353 2354]
   [2355 2356 2357]
   [2358 2359 2360]
   ...
   [2427 2428 2429]
   [2430 2431 2432]
   [2433 2434 2435]]

  [[2436 2437 2438]
   [2439 2440 2441]
   [2442 2443 2444]
   ...
   [2511 2512 2513]
   [2514 2515 2516]
   [2517 2518 2519]]

  [[2520 2521 2522]
   [2523 2524 2525]
   [2526 2527 2528]
   ...
   [2595 2596 2597]
   [2598 2599 2600]
   [2601 2602 2603]]

  ...

  [[4452 4453 4454]
   [4455 4456 4457]
   [4458 4459 4460]
   ...
   [4527 4528 4529]
   [4530 4531 4532]
   [4533 4534 4535]]

  [[4536 4537 4538]
   [4539 4540 4541]
   [4542 4543 4544]
   ...
   [4611 4612 4613]
   [4614 4615 4616]
   [4617 4618 4619]]

  [[4620 4621 4622]
   [4623 4624 4625]
   [4626 4627 4628]
   ...
   [4695 4696 4697]
   [4698 4699 4700]
   [4701 4702 4703]]]]


In [8]:
#索引没有对原始的张量进行修改，而切片进行了修改
#索引0 2 4 6 即可取出第1 3 5 7张图片

In [9]:
#切片取出第6-8张（包括6不包括8）图片中中心区域（14*14）的部分
c = tf.slice(new_a,[5,14,14,0],[2,1,1,3])
with tf.Session() as sess:
    res_3 = sess.run(c)
    print(res_3)

[[[[12978 12979 12980]]]


 [[[15330 15331 15332]]]]


In [10]:
#将图片切片，每一个通道为一张图片
new_a_1 = tf.slice(new_a,[0,0,0,0],[10,28,28,1])
new_a_2 = tf.slice(new_a,[0,0,0,1],[10,28,28,1])
new_a_3 = tf.slice(new_a,[0,0,0,2],[10,28,28,1])
with tf.Session() as sess:
    res_4 = sess.run(new_a_1)
    res_5 = sess.run(new_a_2)
    res_6 = sess.run(new_a_3)
    print(res_4)
    print(res_5)
    print(res_6)

[[[[    0]
   [    3]
   [    6]
   ...
   [   75]
   [   78]
   [   81]]

  [[   84]
   [   87]
   [   90]
   ...
   [  159]
   [  162]
   [  165]]

  [[  168]
   [  171]
   [  174]
   ...
   [  243]
   [  246]
   [  249]]

  ...

  [[ 2100]
   [ 2103]
   [ 2106]
   ...
   [ 2175]
   [ 2178]
   [ 2181]]

  [[ 2184]
   [ 2187]
   [ 2190]
   ...
   [ 2259]
   [ 2262]
   [ 2265]]

  [[ 2268]
   [ 2271]
   [ 2274]
   ...
   [ 2343]
   [ 2346]
   [ 2349]]]


 [[[ 2352]
   [ 2355]
   [ 2358]
   ...
   [ 2427]
   [ 2430]
   [ 2433]]

  [[ 2436]
   [ 2439]
   [ 2442]
   ...
   [ 2511]
   [ 2514]
   [ 2517]]

  [[ 2520]
   [ 2523]
   [ 2526]
   ...
   [ 2595]
   [ 2598]
   [ 2601]]

  ...

  [[ 4452]
   [ 4455]
   [ 4458]
   ...
   [ 4527]
   [ 4530]
   [ 4533]]

  [[ 4536]
   [ 4539]
   [ 4542]
   ...
   [ 4611]
   [ 4614]
   [ 4617]]

  [[ 4620]
   [ 4623]
   [ 4626]
   ...
   [ 4695]
   [ 4698]
   [ 4701]]]


 [[[ 4704]
   [ 4707]
   [ 4710]
   ...
   [ 4779]
   [ 4782]
   [ 4785]]

  [[ 47

In [11]:
#`tf.shape(img)`返回的张量的阶数以及`shape`属性的值
rank = tf.shape(new_a)
print(tf.rank(rank))
print(tf.shape(new_a))

Tensor("Rank:0", shape=(), dtype=int32)
Tensor("Shape_1:0", shape=(4,), dtype=int32)
